/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 571;

var stopwords = Array([lsz]);

stopwords[0] = "a";

stopwords[1] = "a's";

stopwords[2] = "able";

stopwords[3] = "about";

stopwords[4] = "above";

stopwords[5] = "according";

stopwords[6] = "accordingly";

stopwords[7] = "across";

stopwords[8] = "actually";

stopwords[9] = "after";

stopwords[10] = "afterwards";

stopwords[11] = "again";

stopwords[12] = "against";

stopwords[13] = "ain't";

stopwords[14] = "all";

stopwords[15] = "allow";

stopwords[16] = "allows";

stopwords[17] = "almost";

stopwords[18] = "alone";

stopwords[19] = "along";

stopwords[20] = "already";

stopwords[21] = "also";

stopwords[22] = "although";

stopwords[23] = "always";

stopwords[24] = "am";

stopwords[25] = "among";

stopwords[26] = "amongst";

stopwords[27] = "an";

stopwords[28] = "and";

stopwords[29] = "another";

stopwords[30] = "any";

stopwords[31] = "anybody";

stopwords[32] = "anyhow";

stopwords[33] = "anyone";

stopwords[34] = "anything";

stopwords[35] = "anyway";

stopwords[36] = "anyways";

stopwords[37] = "anywhere";

stopwords[38] = "apart";

stopwords[39] = "appear";

stopwords[40] = "appreciate";

stopwords[41] = "appropriate";

stopwords[42] = "are";

stopwords[43] = "aren't";

stopwords[44] = "around";

stopwords[45] = "as";

stopwords[46] = "aside";

stopwords[47] = "ask";

stopwords[48] = "asking";

stopwords[49] = "associated";

stopwords[50] = "at";

stopwords[51] = "available";

stopwords[52] = "away";

stopwords[53] = "awfully";

stopwords[54] = "b";

stopwords[55] = "be";

stopwords[56] = "became";

stopwords[57] = "because";

stopwords[58] = "become";

stopwords[59] = "becomes";

stopwords[60] = "becoming";

stopwords[61] = "been";

stopwords[62] = "before";

stopwords[63] = "beforehand";

stopwords[64] = "behind";

stopwords[65] = "being";

stopwords[66] = "believe";

stopwords[67] = "below";

stopwords[68] = "beside";

stopwords[69] = "besides";

stopwords[70] = "best";

stopwords[71] = "better";

stopwords[72] = "between";

stopwords[73] = "beyond";

stopwords[74] = "both";

stopwords[75] = "brief";

stopwords[76] = "but";

stopwords[77] = "by";

stopwords[78] = "c";

stopwords[79] = "c'mon";

stopwords[80] = "c's";

stopwords[81] = "came";

stopwords[82] = "can";

stopwords[83] = "can't";

stopwords[84] = "cannot";

stopwords[85] = "cant";

stopwords[86] = "cause";

stopwords[87] = "causes";

stopwords[88] = "certain";

stopwords[89] = "certainly";

stopwords[90] = "changes";

stopwords[91] = "clearly";

stopwords[92] = "co";

stopwords[93] = "com";

stopwords[94] = "come";

stopwords[95] = "comes";

stopwords[96] = "concerning";

stopwords[97] = "consequently";

stopwords[98] = "consider";

stopwords[99] = "considering";

stopwords[100] = "contain";

stopwords[101] = "containing";

stopwords[102] = "contains";

stopwords[103] = "corresponding";

stopwords[104] = "could";

stopwords[105] = "couldn't";

stopwords[106] = "course";

stopwords[107] = "currently";

stopwords[108] = "d";

stopwords[109] = "definitely";

stopwords[110] = "described";

stopwords[111] = "despite";

stopwords[112] = "did";

stopwords[113] = "didn't";

stopwords[114] = "different";

stopwords[115] = "do";

stopwords[116] = "does";

stopwords[117] = "doesn't";

stopwords[118] = "doing";

stopwords[119] = "don't";

stopwords[120] = "done";

stopwords[121] = "down";

stopwords[122] = "downwards";

stopwords[123] = "during";

stopwords[124] = "e";

stopwords[125] = "each";

stopwords[126] = "edu";

stopwords[127] = "eg";

stopwords[128] = "eight";

stopwords[129] = "either";

stopwords[130] = "else";

stopwords[131] = "elsewhere";

stopwords[132] = "enough";

stopwords[133] = "entirely";

stopwords[134] = "especially";

stopwords[135] = "et";

stopwords[136] = "etc";

stopwords[137] = "even";

stopwords[138] = "ever";

stopwords[139] = "every";

stopwords[140] = "everybody";

stopwords[141] = "everyone";

stopwords[142] = "everything";

stopwords[143] = "everywhere";

stopwords[144] = "ex";

stopwords[145] = "exactly";

stopwords[146] = "example";

stopwords[147] = "except";

stopwords[148] = "f";

stopwords[149] = "far";

stopwords[150] = "few";

stopwords[151] = "fifth";

stopwords[152] = "first";

stopwords[153] = "five";

stopwords[154] = "followed";

stopwords[155] = "following";

stopwords[156] = "follows";

stopwords[157] = "for";

stopwords[158] = "former";

stopwords[159] = "formerly";

stopwords[160] = "forth";

stopwords[161] = "four";

stopwords[162] = "from";

stopwords[163] = "further";

stopwords[164] = "furthermore";

stopwords[165] = "g";

stopwords[166] = "get";

stopwords[167] = "gets";

stopwords[168] = "getting";

stopwords[169] = "given";

stopwords[170] = "gives";

stopwords[171] = "go";

stopwords[172] = "goes";

stopwords[173] = "going";

stopwords[174] = "gone";

stopwords[175] = "got";

stopwords[176] = "gotten";

stopwords[177] = "greetings";

stopwords[178] = "h";

stopwords[179] = "had";

stopwords[180] = "hadn't";

stopwords[181] = "happens";

stopwords[182] = "hardly";

stopwords[183] = "has";

stopwords[184] = "hasn't";

stopwords[185] = "have";

stopwords[186] = "haven't";

stopwords[187] = "having";

stopwords[188] = "he";

stopwords[189] = "he's";

stopwords[190] = "hello";

stopwords[191] = "help";

stopwords[192] = "hence";

stopwords[193] = "her";

stopwords[194] = "here";

stopwords[195] = "here's";

stopwords[196] = "hereafter";

stopwords[197] = "hereby";

stopwords[198] = "herein";

stopwords[199] = "hereupon";

stopwords[200] = "hers";

stopwords[201] = "herself";

stopwords[202] = "hi";

stopwords[203] = "him";

stopwords[204] = "himself";

stopwords[205] = "his";

stopwords[206] = "hither";

stopwords[207] = "hopefully";

stopwords[208] = "how";

stopwords[209] = "howbeit";

stopwords[210] = "however";

stopwords[211] = "i";

stopwords[212] = "i'd";

stopwords[213] = "i'll";

stopwords[214] = "i'm";

stopwords[215] = "i've";

stopwords[216] = "ie";

stopwords[217] = "if";

stopwords[218] = "ignored";

stopwords[219] = "immediate";

stopwords[220] = "in";

stopwords[221] = "inasmuch";

stopwords[222] = "inc";

stopwords[223] = "indeed";

stopwords[224] = "indicate";

stopwords[225] = "indicated";

stopwords[226] = "indicates";

stopwords[227] = "inner";

stopwords[228] = "insofar";

stopwords[229] = "instead";

stopwords[230] = "into";

stopwords[231] = "inward";

stopwords[232] = "is";

stopwords[233] = "isn't";

stopwords[234] = "it";

stopwords[235] = "it'd";

stopwords[236] = "it'll";

stopwords[237] = "it's";

stopwords[238] = "its";

stopwords[239] = "itself";

stopwords[240] = "j";

stopwords[241] = "just";

stopwords[242] = "k";

stopwords[243] = "keep";

stopwords[244] = "keeps";

stopwords[245] = "kept";

stopwords[246] = "know";

stopwords[247] = "knows";

stopwords[248] = "known";

stopwords[249] = "l";

stopwords[250] = "last";

stopwords[251] = "lately";

stopwords[252] = "later";

stopwords[253] = "latter";

stopwords[254] = "latterly";

stopwords[255] = "least";

stopwords[256] = "less";

stopwords[257] = "lest";

stopwords[258] = "let";

stopwords[259] = "let's";

stopwords[260] = "like";

stopwords[261] = "liked";

stopwords[262] = "likely";

stopwords[263] = "little";

stopwords[264] = "look";

stopwords[265] = "looking";

stopwords[266] = "looks";

stopwords[267] = "ltd";

stopwords[268] = "m";

stopwords[269] = "mainly";

stopwords[270] = "many";

stopwords[271] = "may";

stopwords[272] = "maybe";

stopwords[273] = "me";

stopwords[274] = "mean";

stopwords[275] = "meanwhile";

stopwords[276] = "merely";

stopwords[277] = "might";

stopwords[278] = "more";

stopwords[279] = "moreover";

stopwords[280] = "most";

stopwords[281] = "mostly";

stopwords[282] = "much";

stopwords[283] = "must";

stopwords[284] = "my";

stopwords[285] = "myself";

stopwords[286] = "n";

stopwords[287] = "name";

stopwords[288] = "namely";

stopwords[289] = "nd";

stopwords[290] = "near";

stopwords[291] = "nearly";

stopwords[292] = "necessary";

stopwords[293] = "need";

stopwords[294] = "needs";

stopwords[295] = "neither";

stopwords[296] = "never";

stopwords[297] = "nevertheless";

stopwords[298] = "new";

stopwords[299] = "next";

stopwords[300] = "nine";

stopwords[301] = "no";

stopwords[302] = "nobody";

stopwords[303] = "non";

stopwords[304] = "none";

stopwords[305] = "noone";

stopwords[306] = "nor";

stopwords[307] = "normally";

stopwords[308] = "not";

stopwords[309] = "nothing";

stopwords[310] = "novel";

stopwords[311] = "now";

stopwords[312] = "nowhere";

stopwords[313] = "o";

stopwords[314] = "obviously";

stopwords[315] = "of";

stopwords[316] = "off";

stopwords[317] = "often";

stopwords[318] = "oh";

stopwords[319] = "ok";

stopwords[320] = "okay";

stopwords[321] = "old";

stopwords[322] = "on";

stopwords[323] = "once";

stopwords[324] = "one";

stopwords[325] = "ones";

stopwords[326] = "only";

stopwords[327] = "onto";

stopwords[328] = "or";

stopwords[329] = "other";

stopwords[330] = "others";

stopwords[331] = "otherwise";

stopwords[332] = "ought";

stopwords[333] = "our";

stopwords[334] = "ours";

stopwords[335] = "ourselves";

stopwords[336] = "out";

stopwords[337] = "outside";

stopwords[338] = "over";

stopwords[339] = "overall";

stopwords[340] = "own";

stopwords[341] = "p";

stopwords[342] = "particular";

stopwords[343] = "particularly";

stopwords[344] = "per";

stopwords[345] = "perhaps";

stopwords[346] = "placed";

stopwords[347] = "please";

stopwords[348] = "plus";

stopwords[349] = "possible";

stopwords[350] = "presumably";

stopwords[351] = "probably";

stopwords[352] = "provides";

stopwords[353] = "q";

stopwords[354] = "que";

stopwords[355] = "quite";

stopwords[356] = "qv";

stopwords[357] = "r";

stopwords[358] = "rather";

stopwords[359] = "rd";

stopwords[360] = "re";

stopwords[361] = "really";

stopwords[362] = "reasonably";

stopwords[363] = "regarding";

stopwords[364] = "regardless";

stopwords[365] = "regards";

stopwords[366] = "relatively";

stopwords[367] = "respectively";

stopwords[368] = "right";

stopwords[369] = "s";

stopwords[370] = "said";

stopwords[371] = "same";

stopwords[372] = "saw";

stopwords[373] = "say";

stopwords[374] = "saying";

stopwords[375] = "says";

stopwords[376] = "second";

stopwords[377] = "secondly";

stopwords[378] = "see";

stopwords[379] = "seeing";

stopwords[380] = "seem";

stopwords[381] = "seemed";

stopwords[382] = "seeming";

stopwords[383] = "seems";

stopwords[384] = "seen";

stopwords[385] = "self";

stopwords[386] = "selves";

stopwords[387] = "sensible";

stopwords[388] = "sent";

stopwords[389] = "serious";

stopwords[390] = "seriously";

stopwords[391] = "seven";

stopwords[392] = "several";

stopwords[393] = "shall";

stopwords[394] = "she";

stopwords[395] = "should";

stopwords[396] = "shouldn't";

stopwords[397] = "since";

stopwords[398] = "six";

stopwords[399] = "so";

stopwords[400] = "some";

stopwords[401] = "somebody";

stopwords[402] = "somehow";

stopwords[403] = "someone";

stopwords[404] = "something";

stopwords[405] = "sometime";

stopwords[406] = "sometimes";

stopwords[407] = "somewhat";

stopwords[408] = "somewhere";

stopwords[409] = "soon";

stopwords[410] = "sorry";

stopwords[411] = "specified";

stopwords[412] = "specify";

stopwords[413] = "specifying";

stopwords[414] = "still";

stopwords[415] = "sub";

stopwords[416] = "such";

stopwords[417] = "sup";

stopwords[418] = "sure";

stopwords[419] = "t";

stopwords[420] = "t's";

stopwords[421] = "take";

stopwords[422] = "taken";

stopwords[423] = "tell";

stopwords[424] = "tends";

stopwords[425] = "th";

stopwords[426] = "than";

stopwords[427] = "thank";

stopwords[428] = "thanks";

stopwords[429] = "thanx";

stopwords[430] = "that";

stopwords[431] = "that's";

stopwords[432] = "thats";

stopwords[433] = "the";

stopwords[434] = "their";

stopwords[435] = "theirs";

stopwords[436] = "them";

stopwords[437] = "themselves";

stopwords[438] = "then";

stopwords[439] = "thence";

stopwords[440] = "there";

stopwords[441] = "there's";

stopwords[442] = "thereafter";

stopwords[443] = "thereby";

stopwords[444] = "therefore";

stopwords[445] = "therein";

stopwords[446] = "theres";

stopwords[447] = "thereupon";

stopwords[448] = "these";

stopwords[449] = "they";

stopwords[450] = "they'd";

stopwords[451] = "they'll";

stopwords[452] = "they're";

stopwords[453] = "they've";

stopwords[454] = "think";

stopwords[455] = "third";

stopwords[456] = "this";

stopwords[457] = "thorough";

stopwords[458] = "thoroughly";

stopwords[459] = "those";

stopwords[460] = "though";

stopwords[461] = "three";

stopwords[462] = "through";

stopwords[463] = "throughout";

stopwords[464] = "thru";

stopwords[465] = "thus";

stopwords[466] = "to";

stopwords[467] = "together";

stopwords[468] = "too";

stopwords[469] = "took";

stopwords[470] = "toward";

stopwords[471] = "towards";

stopwords[472] = "tried";

stopwords[473] = "tries";

stopwords[474] = "truly";

stopwords[475] = "try";

stopwords[476] = "trying";

stopwords[477] = "twice";

stopwords[478] = "two";

stopwords[479] = "u";

stopwords[480] = "un";

stopwords[481] = "under";

stopwords[482] = "unfortunately";

stopwords[483] = "unless";

stopwords[484] = "unlikely";

stopwords[485] = "until";

stopwords[486] = "unto";

stopwords[487] = "up";

stopwords[488] = "upon";

stopwords[489] = "us";

stopwords[490] = "use";

stopwords[491] = "used";

stopwords[492] = "useful";

stopwords[493] = "uses";

stopwords[494] = "using";

stopwords[495] = "usually";

stopwords[496] = "uucp";

stopwords[497] = "v";

stopwords[498] = "value";

stopwords[499] = "various";

stopwords[500] = "very";

stopwords[501] = "via";

stopwords[502] = "viz";

stopwords[503] = "vs";

stopwords[504] = "w";

stopwords[505] = "want";

stopwords[506] = "wants";

stopwords[507] = "was";

stopwords[508] = "wasn't";

stopwords[509] = "way";

stopwords[510] = "we";

stopwords[511] = "we'd";

stopwords[512] = "we'll";

stopwords[513] = "we're";

stopwords[514] = "we've";

stopwords[515] = "welcome";

stopwords[516] = "well";

stopwords[517] = "went";

stopwords[518] = "were";

stopwords[519] = "weren't";

stopwords[520] = "what";

stopwords[521] = "what's";

stopwords[522] = "whatever";

stopwords[523] = "when";

stopwords[524] = "whence";

stopwords[525] = "whenever";

stopwords[526] = "where";

stopwords[527] = "where's";

stopwords[528] = "whereafter";

stopwords[529] = "whereas";

stopwords[530] = "whereby";

stopwords[531] = "wherein";

stopwords[532] = "whereupon";

stopwords[533] = "wherever";

stopwords[534] = "whether";

stopwords[535] = "which";

stopwords[536] = "while";

stopwords[537] = "whither";

stopwords[538] = "who";

stopwords[539] = "who's";

stopwords[540] = "whoever";

stopwords[541] = "whole";

stopwords[542] = "whom";

stopwords[543] = "whose";

stopwords[544] = "why";

stopwords[545] = "will";

stopwords[546] = "willing";

stopwords[547] = "wish";

stopwords[548] = "with";

stopwords[549] = "within";

stopwords[550] = "without";

stopwords[551] = "won't";

stopwords[552] = "wonder";

stopwords[553] = "would";

stopwords[554] = "would";

stopwords[555] = "wouldn't";

stopwords[556] = "x";

stopwords[557] = "y";

stopwords[558] = "yes";

stopwords[559] = "yet";

stopwords[560] = "you";

stopwords[561] = "you'd";

stopwords[562] = "you'll";

stopwords[563] = "you're";

stopwords[564] = "you've";

stopwords[565] = "your";

stopwords[566] = "yours";

stopwords[567] = "yourself";

stopwords[568] = "yourselves";

stopwords[569] = "z";

stopwords[570] = "zero";


